const{app,BrowserWindow,ipcMain}=require('electron');
const{spawn}=require('node:child_process');
const{existsSync,mkdirSync,readFileSync,writeFileSync,createReadStream}=require('node:fs');
const{join}=require('node:path');
const{randomUUID,createHash}=require('node:crypto');
let mainWindow,activeJob=null,statusTimer=null,ackTimer=null,activeConfig=null;
function send(channel,payload){if(mainWindow&&!mainWindow.isDestroyed())mainWindow.webContents.send(channel,payload)}
function log(level,message){send('automation:log',{level,message,time:new Date().toLocaleTimeString('zh-CN',{hour12:false})})}
function setState(state,text,action='start'){send('automation:state',{state,text,action})}
function configPath(){return join(app.getPath('userData'),'robot-config.json')}
function ensureConfig(){const path=configPath();if(!existsSync(path))writeFileSync(path,JSON.stringify({shadowBotPath:'E:\\ShadowBot\\ShadowBot.exe',robotUuid:'请替换为已发布流程的UUID',fallbackHotkey:'CTRL+ALT+P',startupAckTimeoutSeconds:15,jobsDirectory:join(app.getPath('documents'),'合众兴自动化任务')},null,2),'utf8');return path}
function loadConfig(){const path=ensureConfig();try{return{path,value:{fallbackHotkey:'CTRL+ALT+P',startupAckTimeoutSeconds:15,...JSON.parse(readFileSync(path,'utf8'))}}}catch(error){throw new Error(`配置文件无法读取：${path}（${error.message}）`)}}
function findShadowBot(){const configured=loadConfig().value.shadowBotPath;const candidates=['E:\\ShadowBot\\ShadowBot.exe',configured,process.env.ProgramFiles&&join(process.env.ProgramFiles,'ShadowBot','ShadowBot.exe'),process.env['ProgramFiles(x86)']&&join(process.env['ProgramFiles(x86)'],'ShadowBot','ShadowBot.exe'),process.env.LOCALAPPDATA&&join(process.env.LOCALAPPDATA,'Programs','ShadowBot','ShadowBot.exe')].filter(Boolean);return candidates.find(existsSync)||null}
function saveShadowBotPath(path){const current=loadConfig().value;writeFileSync(configPath(),JSON.stringify({...current,shadowBotPath:path},null,2),'utf8')}
function bundledInstallerPath(){return app.isPackaged?join(process.resourcesPath,'vendor','ShadowBot-6.2.23-x64.exe'):join(__dirname,'..','vendor','ShadowBot-6.2.23-x64.exe')}
function sha256(path){return new Promise((resolve,reject)=>{const hash=createHash('sha256');const stream=createReadStream(path);stream.on('error',reject);stream.on('data',chunk=>hash.update(chunk));stream.on('end',()=>resolve(hash.digest('hex')))})}
async function installShadowBot(){if(process.platform!=='win32')throw new Error('影刀安装程序只能在 Windows 中运行');setState('running','正在准备影刀安装','install');const installer=bundledInstallerPath();if(!existsSync(installer))throw new Error('完整安装包中缺少影刀官方安装程序');log('info','正在校验影刀官方安装程序');const digest=await sha256(installer);if(digest!=='249ad1a8f29c39cb25738f19f15a02f63837a35298703e12da62212a213879bd')throw new Error('影刀安装程序校验失败，请重新获取完整安装包');log('success','安装程序校验通过，正在自动打开影刀官方安装界面');await new Promise((resolve,reject)=>{const child=spawn(installer,[],{detached:false,stdio:'ignore',windowsHide:false});child.once('error',error=>reject(new Error(`无法打开影刀安装程序：${error.message}`)));child.once('exit',()=>resolve())});const path=findShadowBot();if(!path){setState('error','尚未检测到影刀','install');throw new Error('未在默认目录检测到影刀；如已安装到自定义目录，请稍后在配置中选择 ShadowBot.exe')}saveShadowBotPath(path);setState('idle','请登录并绑定应用');log('success',`已检测到影刀：${path}`);spawn(path,[],{detached:true,stdio:'ignore',windowsHide:false}).unref();return{path}}
ipcMain.handle('automation:install',installShadowBot);
function watchStatus(jobId,statusPath){clearInterval(statusTimer);let lastStatus='';statusTimer=setInterval(()=>{if(!existsSync(statusPath))return;try{const status=JSON.parse(readFileSync(statusPath,'utf8'));if(status.status===lastStatus)return;lastStatus=status.status;if(status.status==='RUNNING'){clearTimeout(ackTimer);setState('running','正在运行');log('success','RPA 已确认开始运行')}if(status.message)log(status.status==='FAILED'?'error':'info',status.message);if(['SUCCEEDED','FAILED','CANCELLED'].includes(status.status)){clearInterval(statusTimer);clearTimeout(ackTimer);activeJob=null;activeConfig=null;const ok=status.status==='SUCCEEDED';setState(ok?'success':'error',ok?'运行完成':'运行结束');log(ok?'success':'error',`任务 ${jobId} 状态：${status.status}`)}}catch(error){log('error',`状态文件格式错误：${error.message}`)}},1000)}
ipcMain.handle('automation:start',async()=>{if(activeJob)throw new Error(`已有任务正在运行：${activeJob}`);if(process.platform!=='win32')throw new Error('影刀流程只能在 Windows 客户端中启动');const{path,value:config}=loadConfig();if(!existsSync(config.shadowBotPath))throw new Error(`未找到影刀程序，请修改配置：${path}`);if(!/^[0-9a-f]{8}-[0-9a-f-]{27,}$/i.test(config.robotUuid||''))throw new Error(`流程 UUID 未配置或格式不正确：${path}`);const jobId=`job-${new Date().toISOString().replace(/[-:.TZ]/g,'').slice(0,14)}-${randomUUID().slice(0,8)}`;const jobDirectory=join(config.jobsDirectory,jobId);mkdirSync(jobDirectory,{recursive:true});const statusPath=join(jobDirectory,'status.json');writeFileSync(join(jobDirectory,'input.json'),JSON.stringify({jobId,action:'publish_products',createdAt:new Date().toISOString()},null,2));writeFileSync(statusPath,JSON.stringify({jobId,status:'QUEUED',updatedAt:new Date().toISOString()},null,2));writeFileSync(join(config.jobsDirectory,'current-job.json'),JSON.stringify({jobId,jobDirectory},null,2));activeJob=jobId;activeConfig=config;setState('running','正在启动');log('info',`创建任务 ${jobId}`);log('info','正在通过 UUID 调用本机影刀流程');const child=spawn(config.shadowBotPath,[`shadowbot:Run?robot-uuid=${config.robotUuid}`],{detached:true,stdio:'ignore',windowsHide:true});let fallbackRequired=false;await new Promise(resolve=>{child.once('error',error=>{fallbackRequired=true;setState('error','UUID 启动失败','fallback');log('error',`UUID 启动失败：${error.message}`);log('info','可点击“使用热键重试”执行同一任务');resolve()});child.once('spawn',()=>{child.unref();log('success','UUID 启动指令已发送，等待 RPA 回传 RUNNING');watchStatus(jobId,statusPath);const seconds=Math.max(5,Number(config.startupAckTimeoutSeconds)||15);ackTimer=setTimeout(()=>{setState('error','未收到启动确认','fallback');log('error',`${seconds} 秒内未收到 RPA 启动确认，可使用同一按钮发送热键重试`)},seconds*1000);resolve()})});return{jobId,fallbackRequired}});

function hotkeyToSendKeys(hotkey){const parts=String(hotkey||'').toUpperCase().split('+').map(value=>value.trim()).filter(Boolean);const key=parts.at(-1);if(!/^[A-Z0-9]$/.test(key)||parts.slice(0,-1).some(value=>!['CTRL','ALT','SHIFT'].includes(value)))throw new Error('降级热键格式无效，应类似 CTRL+ALT+P');return`${parts.includes('CTRL')?'^':''}${parts.includes('ALT')?'%':''}${parts.includes('SHIFT')?'+':''}${key.toLowerCase()}`}
ipcMain.handle('automation:fallback',async()=>{if(process.platform!=='win32')throw new Error('热键降级只能在 Windows 中使用');if(!activeJob||!activeConfig)throw new Error('当前没有可降级重试的任务');const keys=hotkeyToSendKeys(activeConfig.fallbackHotkey);log('info',`准备发送降级热键 ${activeConfig.fallbackHotkey}`);await new Promise((resolve,reject)=>{const child=spawn('powershell.exe',['-NoProfile','-NonInteractive','-Command',`$wshell=New-Object -ComObject WScript.Shell; $wshell.SendKeys('${keys}')`],{windowsHide:true,stdio:'ignore'});child.once('error',error=>reject(new Error(`热键发送失败：${error.message}`)));child.once('exit',code=>code===0?resolve():reject(new Error(`热键发送失败，PowerShell 退出码 ${code}`)))});setState('running','等待热键启动结果');log('success','降级热键已发送，等待 RPA 回传状态');return{jobId:activeJob}});
function createWindow(){mainWindow=new BrowserWindow({width:980,height:660,minWidth:760,minHeight:540,backgroundColor:'#f3f5f8',autoHideMenuBar:true,webPreferences:{preload:join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true}});const devUrl=process.env.VITE_DEV_SERVER_URL;if(devUrl)mainWindow.loadURL(devUrl);else mainWindow.loadFile(join(__dirname,'..','dist','index.html'));mainWindow.webContents.once('did-finish-load',()=>{log('info',`配置文件：${ensureConfig()}`);if(process.platform==='win32'&&!findShadowBot()){log('info','未检测到影刀，将自动打开内置的官方安装程序');setTimeout(()=>installShadowBot().catch(error=>{log('error',error.message);setState('error','影刀安装未完成','install')}),350)}else if(process.platform==='win32'){setState('idle','请确认影刀已登录');log('success',`已检测到影刀：${findShadowBot()}`)}})}
app.whenReady().then(createWindow);app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit()});app.on('activate',()=>{if(BrowserWindow.getAllWindows().length===0)createWindow()});
